/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IKSFactory, IKSFactoryInterface } from "../IKSFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "outToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "outAmount",
        type: "uint256",
      },
      {
        internalType: "address[]",
        name: "path",
        type: "address[]",
      },
    ],
    name: "exchangeKlayNeg",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class IKSFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IKSFactoryInterface {
    return new utils.Interface(_abi) as IKSFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKSFactory {
    return new Contract(address, _abi, signerOrProvider) as IKSFactory;
  }
}
